"""代码生成相关提示词"""
from .coder import CODER_SYSTEM_PROMPT, CODER_TASK_TEMPLATE
from .fixer import FIXER_SYSTEM_PROMPT, FIXER_TASK_TEMPLATE
from .analyzer import ANALYZER_SYSTEM_PROMPT, SUMMARY_TASK_TEMPLATE

__all__ = [
    'CODER_SYSTEM_PROMPT',
    'CODER_TASK_TEMPLATE',
    'FIXER_SYSTEM_PROMPT',
    'FIXER_TASK_TEMPLATE',
    'ANALYZER_SYSTEM_PROMPT',
    'SUMMARY_TASK_TEMPLATE',
]
